export const GET_LEADERBOARD_DATA = 'GET_LEADERBOARD_DATA';
export const SET_SEARCH_NAME = 'SET_SEARCH_NAME';
export const SET_RANKS_MAP = 'SET_RANKS_MAP';
export const SET_FILTERED_DATA = 'SET_FILTERED_DATA';
